language: php
dist: xenial
before_install:
  - pecl install ssh2
php:
  - '7.1'
  - '7.2'
  - '7.3'
install:
  - composer update
script:
 - ./vendor/bin/phpunit --coverage-clover ./tests/Logs/clover.xml
after_script:
 - php vendor/bin/php-coveralls -v