language: php
dist: xenial
matrix:
  include:
    - php: '7.1'
      addons:
        apt:
          packages:
            - php-ssh2
install:
  - composer update
script:
 - ./vendor/bin/phpunit --coverage-clover ./tests/Logs/clover.xml
after_script:
 - php vendor/bin/php-coveralls -v