language: php
dist: xenial
before_install:
  - sudo apt-get install -y -qq libssh2-1-dev libssh2-php
  - pecl install -f ssh2-beta < .noninteractive
php:
  - '7.1'
  - '7.2'
  - '7.3'
install:
  - composer update
script:
 - ./vendor/bin/phpunit --coverage-clover ./tests/Logs/clover.xml
after_script:
 - php vendor/bin/php-coveralls -v