language: php
dist: xenial
apt_packages:
  - php-ssh2
php:
  - '7.0'
install:
  - composer update
script:
 - ./vendor/bin/phpunit --coverage-clover ./tests/Logs/clover.xml
after_script:
 - php vendor/bin/php-coveralls -v