language: php
dist: xenial
matrix:
  include:
    - php: '7.1'
      before_install:
        - sudo apt-get install software-properties-common
        - sudo add-apt-repository ppa:ondrej/php -y
        - sudo apt-get update
        - sudo apt-get install -y php7.1-ssh2
install:
  - composer update
script:
 - ./vendor/bin/phpunit --coverage-clover ./tests/Logs/clover.xml
after_script:
 - php vendor/bin/php-coveralls -v