language: php
dist: xenial
before_install:
  - sudo apt-get update
  - sudo apt-get install -y php7.1-ssh2
  - sudo apt-get install -y php7.2-ssh2
  - sudo apt-get install -y php7.3-ssh2
php:
  - '7.1'
  - '7.2'
  - '7.3'
install:
  - composer update
script:
 - ./vendor/bin/phpunit --coverage-clover ./tests/Logs/clover.xml
after_script:
 - php vendor/bin/php-coveralls -v